# Generated by Django 5.2.7 on 2025-10-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0001_initial"),
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="table",
        ),
        migrations.AddField(
            model_name="reservation",
            name="tables",
            field=models.ManyToManyField(
                related_name="reservations", to="tables.table"
            ),
        ),
    ]
